### ISSUE TITLE
Extension {{ 65037 }} is not Supported by requests 

### ISSUE THREAD

**Issue by xiaoweigege** [wangluozhe/requests-go#16]
65037是扩展算法中的 extensionEncryptedClientHello 请问可以添加吗

**Comment by lxntagram** [comment]
I get requests.exceptions.ConnectionError: [Errno requests_go error:] {"err": "Post "my endpoint": Extension {{ 65037 }} is not Supported by requests please raise an issue"} too

**Comment by wuhua111** [comment]
me too

**Comment by Heartfilia** [comment]
Removing '65037' from ja3_string solves the problem

**Comment by wangluozhe** [comment]
最新版已支持65037了
