### ISSUE TITLE
Ins的ja3会报错

### ISSUE THREAD

**Issue by 760644586** [wangluozhe/requests-go#21]
771,4865-4866-4867,43-10-51-13-0-16-45-41,29-23,

这是Instagram的Ja3  运行会报错

**Comment by 760644586** [comment]
[JA4: t00d0307h2_55b375c5d22e_8f5d6a331b25]
[JA4_r: t00d0307h2_1301,1302,1303_000a,000d,002b,002d,0033_0403,0503,0603,0804]
[JA3 Fullstring: 771,4865-4866-4867,43-10-51-13-0-16-45,29-23,]

**Comment by shijie2951** [comment]
用来请求ins会报错，你解决这个问题了吗?
