### ISSUE TITLE
用tls 的话  程序会抛异常

### ISSUE THREAD

**Issue by qiaolang** [wangluozhe/requests-go#5]
r = requests_go.post(url, json=data,  headers=headers, tls_config=tc)

File "D:\Users\qiaoqiao\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by wangluozhe** [comment]
请把你完整代码给我一下

**Comment by wangluozhe** [comment]
0.3和0.4版本已修复这个情况
